# -*- coding: utf-8 -*-
"""CORTE DE INTERVALOS COLUMNAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXI5mLfp2HwqBcAUFDo3egzEPCS3eQXr
"""

"""
================================================================
CORTE DE INTERVALOS - MODO MANUAL (CORREGIDO PARA COLAB)
================================================================
Eventos en segundos -> se convierten a milisegundos
para coincidir con la columna t_exp del Excel.
================================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# ============================================================
# PERFILES (eventos en SEGUNDOS, con nombres descriptivos)
# ============================================================
PERFILES = {
    '8110': {
        'nombres': [
            '01_Inicio_agua_miliQ',
            '02_Parada_bomba_explosion',
            '03_Final_grabacion',
        ],
        'eventos': [
            (216, "Parada_bomba_explosion"),  # 3:36 min
        ],
    },
    '8112': {
        'nombres': [
            '01_Inicio_agua_miliQ',
            '02_Set_absorbancia_0',
            '03_Entrada_aire_1',
            '04_Recuperacion_agua',
            '05_Set_absorbancia_0_2',
            '06_Columna_tapada_1',
            '07_Columna_tapada_2',
            '08_Final',
        ],
        'eventos': [
            (18,  "Set_absorbancia_0"),
            (180, "Entrada_aire_1"),
            (240, "Recuperacion_agua"),
            (337, "Set_absorbancia_0_2"),
            (460, "Columna_tapada_1"),
            (493, "Columna_tapada_2"),
        ],
    },
    '8102': {
        'nombres': [
            '01_Buffer_pH55',
            '02_Pausa_bomba_1',
            '03_Sigue_bomba_1',
            '04_RodaminaB_08',
            '05_Pausa_bomba_2',
            '06_Sigue_bomba_2',
            '07_Lavado_Buffer',
            '08_Final',
        ],
        'eventos': [
            (255, "Pausa_bomba_1"),
            (270, "Sigue_bomba_1_y_cambia_a_RodaminaB_08"),
            (329, "Pausa_bomba_2_y_cambia_a_Buffer"),
            (338, "Sigue_bomba_2"),
        ],
    },
    '8106': {
        'nombres': [
            '01_Agua_miliQ_inicial',
            '02_Pausa_bomba_agua',
            '03_Sigue_agua',
            '04_Buffer_pH55',
            '05_Pausa_bomba_buffer',
            '06_Sigue_buffer',
            '07_RodaminaB_05',
            '08_Pausa_bomba_05',
            '09_Sigue_RodaminaB_05',
            '10_RodaminaB_08',
            '11_Pausa_bomba_08',
            '12_Sigue_RodaminaB_08',
            '13_RodaminaB_10',
            '14_Pausa_bomba_10',
            '15_Sigue_RodaminaB_10',
            '16_RodaminaB_13',
            '17_Pausa_bomba_13',
            '18_Sigue_RodaminaB_13',
            '19_Lavado_Buffer',
            '20_Pausa_bomba_lavado',
            '21_Sigue_lavado',
            '22_Agua_final',
            '23_Pausa_final_1',
            '24_Sigue_final_1',
            '25_Agua_final_2',
            '26_Pausa_final_2',
            '27_Sigue_final_2',
            '28_Agua_final_3',
            '29_Pausa_final_3',
            '30_Sigue_final_3',
            '31_Agua_final_4',
            '32_Pausa_final_4',
            '33_Sigue_final_4',
            '34_Final',
        ],
        'eventos': [
            (1022, "Pausa_bomba_agua"),
            (1034, "Inicio_Buffer_pH55"),
            (1663, "Pausa_bomba_buffer"),
            (1686, "Inicio_RodaminaB_05"),
            (1725, "Pausa_bomba_05"),
            (1736, "Inicio_RodaminaB_08"),
            (2291, "Pausa_bomba_08"),
            (2305, "Inicio_RodaminaB_10"),
            (2353, "Pausa_bomba_10"),
            (2360, "Inicio_RodaminaB_13"),
            (2770, "Pausa_bomba_13"),
            (2782, "Inicio_Lavado_Buffer"),
            (2813, "Pausa_bomba_lavado"),
            (2822, "Inicio_Agua_final"),
            (3247, "Pausa_final_1"),
            (3259, "Inicio_Agua_2"),
            (3291, "Pausa_final_2"),
            (3300, "Inicio_Agua_3"),
            (3836, "Pausa_final_3"),
            (3857, "Inicio_Agua_4"),
            (3950, "Pausa_final_4"),
            (3962, "Sigue_final_4"),
            (4480, "Final"),
        ],
    },
}

# ============================================================
# CONVERSION: eventos de segundos a milisegundos
# ============================================================
def convertir_eventos_a_ms(eventos):
    """Convierte los tiempos de eventos de segundos a milisegundos."""
    return [(int(t * 1000), nombre) for t, nombre in eventos]


# ============================================================
# FUNCIONES
# ============================================================

def cargar(archivo):
    """Carga CSV o Excel."""
    if archivo.endswith('.csv'):
        df = pd.read_csv(archivo)
    else:
        df = pd.read_excel(archivo)
    return df['t_exp'].values.astype(float), df['absorbancia'].values.astype(float)


def cortar(t, A, eventos, nombres, carpeta):
    """Corta intervalos y guarda CSVs."""
    os.makedirs(carpeta, exist_ok=True)

    # Extraer solo los tiempos de los eventos (ya en ms)
    tiempos_eventos = [e[0] for e in eventos]
    tiempos = [t[0]] + tiempos_eventos + [t[-1]]

    for i in range(len(tiempos) - 1):
        ini, fin = tiempos[i], tiempos[i+1]
        mask = (t >= ini) & (t <= fin)

        if mask.sum() == 0:
            continue

        nombre = nombres[i] if i < len(nombres) else f'Int_{i+1:02d}'
        pd.DataFrame({
            't_exp': t[mask],
            'absorbancia': A[mask]
        }).to_csv(f"{carpeta}/{nombre}.csv", index=False)
        print(f"  {nombre}: {ini:.0f}-{fin:.0f} ms ({mask.sum()} pts)")


def graficar(t, A, eventos, carpeta, titulo):
    """Grafica curva con eventos marcados."""
    fig, ax = plt.subplots(figsize=(16, 7))
    ax.plot(t, A, 'b-', linewidth=1.2, label='Absorbancia')

    colores = ['red', 'green', 'orange', 'purple', 'brown',
               'pink', 'gray', 'olive', 'cyan', 'magenta']

    for i, (tiempo, nombre) in enumerate(eventos):
        color = colores[i % len(colores)]
        ax.axvline(tiempo, color=color, linestyle='--', linewidth=1.5, alpha=0.8)
        ax.text(tiempo, ax.get_ylim()[1] * 0.95,
                f'{nombre}\n({tiempo/1000:.0f}s)',
                rotation=90, verticalalignment='top',
                fontsize=7, color=color, alpha=0.9,
                bbox=dict(boxstyle='round,pad=0.2', facecolor='white',
                          edgecolor=color, alpha=0.7))

    ax.set_xlabel('Tiempo (ms)', fontsize=12)
    ax.set_ylabel('Absorbancia', fontsize=12)
    ax.set_title(titulo, fontsize=14)
    ax.grid(True, linestyle='--', alpha=0.3)
    ax.set_ylim(bottom=ax.get_ylim()[0], top=ax.get_ylim()[1] * 1.15)

    plt.tight_layout()
    plt.savefig(f"{carpeta}/grafico_eventos.png", dpi=150)
    plt.show()
    print(f"  Grafico: {carpeta}/grafico_eventos.png")


# ============================================================
# EJECUCION
# ============================================================

archivo = input("Archivo a procesar (ej. absorbancia8110.xlsx): ").strip().strip('"').strip("'")

# Detectar perfil
perfil_key = None
for key in PERFILES:
    if key in archivo:
        perfil_key = key
        break

if perfil_key is None:
    print(f"Error: No se reconoce el perfil para '{archivo}'")
    print(f"Perfiles disponibles: {list(PERFILES.keys())}")
    exit()

perfil = PERFILES[perfil_key]
print(f"\nPerfil detectado: {perfil_key}")
print(f"Datos: {archivo}")

# Cargar datos
t, A = cargar(archivo)
print(f"Puntos: {len(t)}, tiempo: {t[0]:.0f}-{t[-1]:.0f} ms")

# Convertir eventos de segundos a milisegundos
eventos_ms = convertir_eventos_a_ms(perfil['eventos'])
print(f"\nEventos convertidos a ms:")
for tiempo, nombre in eventos_ms:
    print(f"  {nombre}: {tiempo} ms")

# Cortar intervalos
carpeta = f"intervalos_{perfil_key}"
print(f"\nIntervalos generados:")
cortar(t, A, eventos_ms, perfil['nombres'], carpeta)

# Graficar
graficar(t, A, eventos_ms, carpeta, f'Absorbancia vs Tiempo - {perfil_key}')

print(f"\nListo! Resultados en: {carpeta}/")