# -*- coding: utf-8 -*-
"""Columnasreynolds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vr9qcMcswdZgNqwJJkCg0-Yn4Tbq_7x
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm


def calcular_reynolds(Q, D, rho, mu):
    """
    Calcula el número de Reynolds en función del caudal volumétrico Q.

    Re = rho * v * D / mu,  con v = Q / A y A = pi * D^2 / 4
    => Re = 4 * rho * Q / (pi * D * mu)

    Parámetros
    ----------
    Q   : caudal volumétrico [m³/s] (float o array)
    D   : diámetro de la columna/tubería [m]
    rho : densidad del fluido [kg/m³]
    mu  : viscosidad dinámica del fluido [Pa·s]
    """
    return 4.0 * rho * Q / (np.pi * D * mu)


def graficar_reynolds(Q, Re, log_scale=False):
    """Genera el gráfico de Re = Re(Q).

    log_scale : bool, si es True usa escala logarítmica en ambos ejes,
                si es False usa escala lineal.
    """
    plt.figure(figsize=(10, 6))

    plt.plot(Q, Re, color="tab:blue", linewidth=2)

    # ============================================================
    # ANOTACIONES DE REGÍMENES DE FLUJO
    # ============================================================
    plt.axhline(2300, color="black", linestyle="--", linewidth=1)
    plt.axhline(4000, color="black", linestyle="--", linewidth=1)

    plt.text(
        Q.min(),
        2300,
        "Re = 2300 (Laminar -> Transición)",
        fontsize=9,
        va="bottom",
        ha="left",
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.7),
    )
    plt.text(
        Q.min(),
        4000,
        "Re = 4000 (Transición -> Turbulento)",
        fontsize=9,
        va="bottom",
        ha="left",
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.7),
    )

    # ============================================================
    # FORMATO DEL GRÁFICO
    # ============================================================
    plt.xlabel("Caudal volumétrico Q [m³/s]", fontsize=12)
    plt.ylabel("Número de Reynolds (Re)", fontsize=12)
    plt.title("Número de Reynolds en función del caudal (Re = Re(Q))", fontsize=14)
    plt.grid(True, linestyle="--", alpha=0.4)
    if log_scale:
        plt.xscale("log")
        plt.yscale("log")
    plt.tight_layout()

    plt.show()


def graficar_contorno_reynolds(
    Q,
    D,
    rho,
    mu,
    log_scale=False,
    diametros_mercado=None,
    Q_real=None,
    D_real=None,
):
    """Genera el gráfico de contorno de Re = Re(Q, D).

    Q, D : arrays 1D con los rangos de caudal volumétrico [m³/s] y de
           diámetro de columna [m] a evaluar (diámetros comerciales).
    log_scale : bool, si es True usa escala logarítmica en los ejes X e Y.
    diametros_mercado : lista de diámetros comerciales disponibles [m] a
           marcar como líneas horizontales de referencia.
    Q_real : caudal real de operación [m³/s] (canal de riego) a marcar
           como línea vertical.
    D_real : diámetro real del canal [m]. No se grafica directamente (su
           escala es muy distinta a la de los diámetros comerciales), pero
           junto con Q_real define el Re_real del caso real, que se marca
           como curva de contorno para poder comparar regímenes.
    """
    QQ, DD = np.meshgrid(Q, D)
    Re = calcular_reynolds(QQ, DD, rho, mu)

    plt.figure(figsize=(10, 6))

    contourf = plt.contourf(
        QQ, DD, Re, levels=np.logspace(np.log10(Re.min()), np.log10(Re.max()), 50),
        norm=LogNorm(), cmap="viridis",
    )
    plt.colorbar(contourf, label="Número de Reynolds (Re)")

    # Contornos de referencia (órdenes de magnitud de Re)
    ref_levels = [lvl for lvl in [100, 1000, 10000, 100000] if Re.min() < lvl < Re.max()]
    if ref_levels:
        contour = plt.contour(QQ, DD, Re, levels=ref_levels, colors="black", linewidths=1.0)
        plt.clabel(contour, inline=True, fontsize=9, fmt="%d")

    # Entradas de leyenda acumuladas (las líneas de régimen y el caso real
    # quedan demasiado juntas entre sí para etiquetarlas inline sobre el
    # gráfico, así que se identifican mediante la leyenda).
    leyenda_handles = []

    # ============================================================
    # LÍMITES DE RÉGIMEN LAMINAR / TRANSICIÓN / TURBULENTO
    # (laminar: Re < 2300, transición: 2300 < Re < 4000, turbulento: Re > 4000)
    # ============================================================
    color_regimen = {2300: "tab:blue", 4000: "tab:red"}
    etiqueta_regimen = {2300: "Re=2300 (Laminar→Transición)", 4000: "Re=4000 (Transición→Turbulento)"}
    regimen_en_rango = [lvl for lvl in (2300, 4000) if Re.min() < lvl < Re.max()]
    for lvl in regimen_en_rango:
        plt.contour(
            QQ, DD, Re, levels=[lvl], colors=color_regimen[lvl], linewidths=2, linestyles="--"
        )
        leyenda_handles.append(
            plt.Line2D([], [], color=color_regimen[lvl], linestyle="--", linewidth=2, label=etiqueta_regimen[lvl])
        )

    # ============================================================
    # DIÁMETROS DISPONIBLES EN EL MERCADO
    # ============================================================
    if diametros_mercado is not None:
        for d in diametros_mercado:
            plt.axhline(d, color="white", linestyle=":", linewidth=1.2)
            plt.text(
                Q.max(),
                d,
                f"D = {d * 1000:.0f} mm",
                fontsize=8,
                color="white",
                va="bottom",
                ha="right",
            )

    # ============================================================
    # CASO REAL (CANAL DE RIEGO): Q_real, D_real -> Re_real
    # ============================================================
    Re_real = None
    if Q_real is not None and D_real is not None:
        Re_real = calcular_reynolds(Q_real, D_real, rho, mu)
        if Re.min() < Re_real < Re.max():
            plt.contour(QQ, DD, Re, levels=[Re_real], colors="gold", linewidths=2.5)
            leyenda_handles.append(
                plt.Line2D(
                    [], [], color="gold", linewidth=2.5,
                    label=f"Re_real={Re_real:.0f} (canal D={D_real * 1000:.0f} mm, Q={Q_real:.2e} m³/s)",
                )
            )

    # ============================================================
    # CAUDAL REAL DE OPERACIÓN (Q_real)
    # ============================================================
    if Q_real is not None:
        plt.axvline(
            Q_real,
            color="red",
            linestyle="-",
            linewidth=2,
            label=f"Q_real = {Q_real:.2e} m³/s",
        )

        # Intersección con los diámetros de mercado: marca el Re resultante
        # y resalta el diámetro comercial cuyo Re queda más cerca de Re_real
        if diametros_mercado is not None:
            re_mercado = np.array(
                [calcular_reynolds(Q_real, d, rho, mu) for d in diametros_mercado]
            )
            idx_mejor = None
            if Re_real is not None:
                idx_mejor = int(np.argmin(np.abs(re_mercado - Re_real)))

            for i, d in enumerate(diametros_mercado):
                es_mejor = i == idx_mejor
                plt.plot(
                    Q_real,
                    d,
                    "*" if es_mejor else "o",
                    color="gold" if es_mejor else "red",
                    markersize=14 if es_mejor else 6,
                    markeredgecolor="black" if es_mejor else None,
                    zorder=5 if es_mejor else 3,
                )
                plt.annotate(
                    f"Re={re_mercado[i]:.0f}",
                    (Q_real, d),
                    textcoords="offset points",
                    xytext=(8, 8),
                    fontsize=8,
                    color="gold" if es_mejor else "red",
                    fontweight="bold" if es_mejor else "normal",
                )

            if idx_mejor is not None:
                plt.plot(
                    [], [], "*", color="gold", markersize=14, markeredgecolor="black",
                    label=f"Diámetro recomendado: {diametros_mercado[idx_mejor] * 1000:.0f} mm "
                    f"(Re más cercano a Re_real)",
                )
                print(
                    f"Re_real (canal D_real={D_real:.3f} m, Q_real={Q_real:.2e} m³/s) = {Re_real:.0f}"
                )
                print(
                    f"Diámetro comercial recomendado: {diametros_mercado[idx_mejor] * 1000:.0f} mm "
                    f"(Re={re_mercado[idx_mejor]:.0f})"
                )

        handles, _ = plt.gca().get_legend_handles_labels()
        plt.legend(handles=handles + leyenda_handles, loc="lower right", fontsize=9)

    plt.xlabel("Caudal volumétrico Q [m³/s]")
    plt.ylabel("Diámetro de columna D [m]")
    plt.title("Número de Reynolds (Re = Re(Q, D))")
    plt.grid(True, linestyle="--", alpha=0.4)

    if log_scale:
        plt.xscale("log")
        plt.yscale("log")

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    # ============================================================
    # PARÁMETROS DEL FLUIDO (Agua a 20°C, si es otra temperatura,
    # los datos los podemos sacar de las tablas Cengel)
    # ============================================================

    # Propiedades
    rho = 1000.0  # densidad [kg/m³]
    mu = 0.001  # viscosidad dinámica [Pa·s]

    # Diámetros comerciales disponibles en aliexpress
    diametros_mercado = np.array(
        [4, 22, 21, 20, 18, 16, 12, 14, 11, 10, 8, 7, 6, 5]
    )  # en milimetros
    diametros_mercado_m = diametros_mercado / 1000.0  # convertir a metros

    # Caudal y diámetro reales de operación (canal de riego)
    Q_real = 0.001  # 1 L/s
    D_real = 0.5  # diámetro real del canal, 0.5 m

    # Rango de diámetros de columna: ajustado a los diámetros comerciales
    # disponibles (4-22 mm), con un pequeño margen para que todas las
    # líneas de referencia queden dentro del gráfico.
    D_min = diametros_mercado_m.min() * 0.8
    D_max = diametros_mercado_m.max() * 1.15
    num_D = 100

    # Rango de caudal: se extiende hacia valores bajos para poder mostrar
    # dentro de la superficie las fronteras de régimen (Re=2300 y Re=4000)
    # y el Re_real del canal, además de Q_real como línea vertical.
    Q_min = 1e-6
    Q_max = Q_real * 1.5
    num_Q = 200

    Q_rango = np.logspace(np.log10(Q_min), np.log10(Q_max), num_Q)
    D_rango = np.linspace(D_min, D_max, num_D)

    graficar_contorno_reynolds(
        Q_rango,
        D_rango,
        rho,
        mu,
        log_scale=True,
        diametros_mercado=diametros_mercado_m,
        Q_real=Q_real,
        D_real=D_real,
    )
